from django.db import models

class locationModel(models.Model):
    COUNTRY_CHOICES=(
        ('UK', 'UK'),
        ('France', 'France'),
        ('Australia', 'Australia'),
        ('Japan', 'Japan'),
        ('India', 'India'),
        ('China', 'China'),
        ('Germany', 'Germany'),
        ('Spain', 'Spain'),
        ('Italy', 'Italy'),
        ('Russian', 'Russian'),
        ('Greece', 'Greece'),
        ('Türkiye', 'Türkiye'),
        ('USA', 'USA'),
        ('Egypt', 'Egypt'),
        ('Algiers', 'Algiers'),
        ('Tunis', 'Tunis'),
        ('Syrian Arab', 'Syrian Arab'),
        ('Lebanon', 'Lebanon'),
        ('Kuwait', 'Kuwait'),
        ('UAE', 'UAE'),
        ('Qatar', 'Qatar'),
    )
    CITY_CHOICES = (
        ('london', 'London'),
        ('paris', 'Paris'),
        ('Sydney', 'Sydney'),
        ('Tokyo', 'Tokyo'),
        ('Chennai', 'Chennai'),
        ('Delhi', 'Delhi'),
        ('Hong Kong', 'Hong Kong'),
        ('Berlin', 'Berlin'),
        ('Madrid', 'Madrid'),
        ('Rome', 'Rome'),
        ('Barcelona', 'Barcelona'),
        ('Moscow', 'Moscow'),
        ('Athens', 'Athens'),
        ('Istanbul', 'Istanbul'),
        ('Los Angeles', 'Los Angeles'),
        ('Miami', 'Miami'),
        ('San Francisco', 'San Francisco'),
        ('Mexico', 'Mexico'),
        ('Cairo', 'Cairo'),
        ('Algiers', 'Algiers'),
        ('Vienna', 'Vienna'),
        ('Berlin', 'Berlin'),
        ('Alexandria', 'Alexandria'),
        ('Tunis', 'Tunis'),
        ('Giza', 'Giza'),
        ('Ankara', 'Ankara'),
        ('Beirut', 'Beirut'),
        ('Izmir', 'Izmir'),
        ('Damascus', 'Damascus'),
        ('Kuwait', 'Kuwait'),
        ('Dubai', 'Dubai'),
        ('Abu Dhabi', 'Abu Dhabi'),
        ('Doha', 'Doha'),
    )
    country = models.CharField(max_length=50, choices=COUNTRY_CHOICES)
    city = models.CharField(max_length=50, choices=CITY_CHOICES,unique=True)
    