# Generated by Django 4.2.15 on 2024-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UK', 'UK'), ('France', 'France'), ('Australia', 'Australia'), ('Japan', 'Japan'), ('India', 'India'), ('China', 'China'), ('Germany', 'Germany'), ('Spain', 'Spain'), ('Italy', 'Italy'), ('Russian', 'Russian'), ('Greece', 'Greece'), ('Türkiye', 'Türkiye'), ('USA', 'USA'), ('Egypt', 'Egypt'), ('Algiers', 'Algiers'), ('Tunis', 'Tunis'), ('Syrian Arab', 'Syrian Arab'), ('Lebanon', 'Lebanon'), ('Kuwait', 'Kuwait'), ('UAE', 'UAE'), ('Qatar', 'Qatar')], max_length=50)),
                ('city', models.CharField(choices=[('london', 'London'), ('paris', 'Paris'), ('Sydney', 'Sydney'), ('Tokyo', 'Tokyo'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Hong Kong', 'Hong Kong'), ('Berlin', 'Berlin'), ('Madrid', 'Madrid'), ('Rome', 'Rome'), ('Barcelona', 'Barcelona'), ('Moscow', 'Moscow'), ('Athens', 'Athens'), ('Istanbul', 'Istanbul'), ('Los Angeles', 'Los Angeles'), ('Miami', 'Miami'), ('San Francisco', 'San Francisco'), ('Mexico', 'Mexico'), ('Cairo', 'Cairo'), ('Algiers', 'Algiers'), ('Vienna', 'Vienna'), ('Berlin', 'Berlin'), ('Alexandria', 'Alexandria'), ('Tunis', 'Tunis'), ('Giza', 'Giza'), ('Ankara', 'Ankara'), ('Beirut', 'Beirut'), ('Izmir', 'Izmir'), ('Damascus', 'Damascus'), ('Kuwait', 'Kuwait'), ('Dubai', 'Dubai'), ('Abu Dhabi', 'Abu Dhabi'), ('Doha', 'Doha')], max_length=50, unique=True)),
            ],
        ),
    ]
