# Generated by Django 5.1 on 2024-09-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_blacklisttoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklisttoken',
            old_name='blacklisted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='blacklisttoken',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
