# Generated by Django 5.1 on 2024-09-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_rename_blacklisted_at_blacklisttoken_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistToken',
        ),
    ]
