# Generated by Django 4.2.16 on 2024-09-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('london', 'London'), ('paris', 'Paris'), ('Sydney', 'Sydney'), ('Tokyo', 'Tokyo'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Hong_Kong', 'Hong Kong'), ('Berlin', 'Berlin'), ('Madrid', 'Madrid'), ('Rome', 'Rome'), ('Barcelona', 'Barcelona'), ('Moscow', 'Moscow'), ('Athens', 'Athens'), ('Istanbul', 'Istanbul'), ('Los_Angeles', 'Los Angeles'), ('Miami', 'Miami'), ('San_Francisco', 'San Francisco'), ('Mexico', 'Mexico'), ('Cairo', 'Cairo'), ('Algiers', 'Algiers'), ('Berlin', 'Berlin'), ('Vienna', 'Vienna'), ('Amsterdam', 'Amsterdam'), ('Berlin', 'Berlin'), ('Alexandria', 'Alexandria'), ('Tunis', 'Tunis'), ('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Giza', 'Giza'), ('Ankara', 'Ankara'), ('Beirut', 'Beirut'), ('Izmir', 'Izmir'), ('Damascus', 'Damascus'), ('Amman', 'Amman'), ('Kuwait', 'Kuwait'), ('Dubai', 'Dubai'), ('Abu_Dhabi', 'Abu Dhabi'), ('Doha', 'Doha')], max_length=50)),
                ('city', models.CharField(choices=[('london', 'London'), ('paris', 'Paris'), ('Sydney', 'Sydney'), ('Tokyo', 'Tokyo'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Hong_Kong', 'Hong Kong'), ('Berlin', 'Berlin'), ('Madrid', 'Madrid'), ('Rome', 'Rome'), ('Barcelona', 'Barcelona'), ('Moscow', 'Moscow'), ('Athens', 'Athens'), ('Istanbul', 'Istanbul'), ('Los_Angeles', 'Los Angeles'), ('Miami', 'Miami'), ('San_Francisco', 'San Francisco'), ('Mexico', 'Mexico'), ('Cairo', 'Cairo'), ('Algiers', 'Algiers'), ('Berlin', 'Berlin'), ('Vienna', 'Vienna'), ('Amsterdam', 'Amsterdam'), ('Berlin', 'Berlin'), ('Alexandria', 'Alexandria'), ('Tunis', 'Tunis'), ('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Giza', 'Giza'), ('Ankara', 'Ankara'), ('Beirut', 'Beirut'), ('Izmir', 'Izmir'), ('Damascus', 'Damascus'), ('Amman', 'Amman'), ('Kuwait', 'Kuwait'), ('Dubai', 'Dubai'), ('Abu_Dhabi', 'Abu Dhabi'), ('Doha', 'Doha')], max_length=50)),
            ],
        ),
    ]
