# Generated by Django 5.1 on 2024-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='country',
            field=models.CharField(choices=[('london', 'London'), ('paris', 'Paris'), ('Sydney', 'Sydney'), ('Tokyo', 'Tokyo'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Hong_Kong', 'Hong Kong'), ('Berlin', 'Berlin'), ('Madrid', 'Madrid'), ('Rome', 'Rome'), ('Barcelona', 'Barcelona'), ('Moscow', 'Moscow'), ('Athens', 'Athens'), ('Istanbul', 'Istanbul'), ('Los_Angeles', 'Los Angeles'), ('Miami', 'Miami'), ('San_Francisco', 'San Francisco'), ('Mexico', 'Mexico'), ('Cairo', 'Cairo'), ('Algiers', 'Algiers'), ('Berlin', 'Berlin'), ('Vienna', 'Vienna'), ('Amsterdam', 'Amsterdam'), ('Berlin', 'Berlin'), ('Alexandria', 'Alexandria'), ('Tunis', 'Tunis'), ('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Giza', 'Giza'), ('Ankara', 'Ankara'), ('Beirut', 'Beirut'), ('Izmir', 'Izmir'), ('Damascus', 'Damascus'), ('Amman', 'Amman'), ('Kuwait', 'Kuwait'), ('Dubai', 'Dubai'), ('Abu_Dhabi', 'Abu Dhabi'), ('Doha', 'Doha')], max_length=50),
        ),
    ]
