# Generated by Django 4.2.16 on 2024-09-11 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('Trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Befor', models.DateField()),
                ('Shipment_Name', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Weight', models.FloatField()),
                ('Price', models.FloatField()),
                ('Reward', models.FloatField(blank=True, null=True)),
                ('Total_Weight', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ship_from_location', to='locations.locationmodel')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ship_to_location', to='locations.locationmodel')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='Trips.trips')),
            ],
            options={
                'ordering': ['Date_Befor'],
            },
        ),
    ]
