<<<<<<< HEAD
# Generated by Django 4.2.15 on 2024-09-08 08:05
=======
# Generated by Django 4.2.16 on 2024-09-04 11:21
>>>>>>> 2b5c8110c22837afafa55ff69e028d00287250ca

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
<<<<<<< HEAD
        ('location', '0001_initial'),
=======
        ('Trips', '0001_initial'),
        ('Locations', '0001_initial'),
>>>>>>> 2b5c8110c22837afafa55ff69e028d00287250ca
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Befor', models.DateField()),
                ('Shipment_Name', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
                ('Weight', models.FloatField()),
                ('Price', models.FloatField()),
                ('Total_Price', models.FloatField(blank=True, null=True)),
                ('Total_Weight', models.FloatField(blank=True, null=True)),
<<<<<<< HEAD
                ('image', models.ImageField(upload_to='images/')),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ship_from_location', to='location.locationmodel')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ship_to_location', to='location.locationmodel')),
                ('Trips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trips.trips')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('From_Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ship_from_location', to='Locations.locationmodel')),
                ('To_Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ship_to_location', to='Locations.locationmodel')),
                ('Trips', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trips.tripsmodel')),
                ('added_by', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
>>>>>>> 2b5c8110c22837afafa55ff69e028d00287250ca
            ],
            options={
                'ordering': ['Date_Befor'],
            },
        ),
    ]
