# Generated by Django 4.2.15 on 2024-09-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipments',
            old_name='Trips',
            new_name='trips',
        ),
    ]
