# Generated by Django 5.1 on 2024-09-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0001_initial'),
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipments',
            name='trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trips.trips'),
        ),
    ]
