# Generated by Django 5.1 on 2024-09-10 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0002_shipments_trips'),
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipments',
            name='trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='Trips.trips'),
        ),
    ]
