# Generated by Django 5.1 on 2024-09-05 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipments', '0005_alter_shipments_image'),
        ('Trips', '0003_remove_trips_total_shipment_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipments',
            options={'ordering': ['Date_Befor']},
        ),
        migrations.AddField(
            model_name='shipments',
            name='Trips',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Trips.trips'),
        ),
    ]
