# Generated by Django 4.2.16 on 2024-09-04 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tripsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_Date', models.DateField()),
                ('depart_Time', models.TimeField()),
                ('FreeWeight', models.FloatField()),
                ('ComsumedWeight', models.FloatField()),
                ('TotolWeight', models.FloatField()),
                ('From_Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_from_location', to='Locations.locationmodel')),
                ('To_Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_to_location', to='Locations.locationmodel')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
