# Generated by Django 5.1 on 2024-09-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locations', '__first__'),
        ('Shipments', '0005_alter_shipments_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_Date', models.DateField()),
                ('depart_Time', models.TimeField()),
                ('FreeWeight', models.FloatField()),
                ('ComsumedWeight', models.FloatField()),
                ('From_Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_from_location', to='Locations.locationmodel')),
                ('To_Field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_to_location', to='Locations.locationmodel')),
                ('Total_Shipment_Weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Shipments.shipments')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
