# Generated by Django 5.1 on 2024-09-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='From_Field',
            new_name='From',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='To_Field',
            new_name='To',
        ),
    ]
