# Generated by Django 5.1 on 2024-09-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0002_rename_from_field_trips_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='Total_Shipment_Weight',
        ),
    ]
